---
apiVersion: v1
kind: Template
metadata:
  labels:
    app: fabric8-online-jenkins
    provider: fabric8
    version: 1.0.294
    group: io.fabric8.online.packages
  name: fabric8-online-jenkins
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
      fabric8.io/git-commit: 419a7981d34eb123d464f03d3978c2b9a790f3df
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-team-components/jenkins-openshift
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-team-components/master/jenkins-openshift/src/main/fabric8/icon.svg
      fabric8.io/git-branch: release-v3.0.91
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
      fabric8.io/scm-tag: fabric8-team-components-1.0.0
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepository/io/fabric8/fabric8-team-components/apps/jenkins-openshift/3.0.91/jenkins-openshift-3.0.91.jar!/META-INF/fabric8/openshift.yml
    labels:
      app: jenkins
      provider: fabric8
      expose: "true"
      version: 3.0.91
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 6666
    selector:
      app: jenkins-openshift
      provider: fabric8
      group: io.fabric8.fabric8-team-components.apps
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/target-platform: openshift
      configmap.fabric8.io/update-on-change: jenkins
      fabric8.io/git-commit: 419a7981d34eb123d464f03d3978c2b9a790f3df
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=jenkins-openshift&var-version=3.0.91
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-team-components/jenkins-openshift
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-team-components/master/jenkins-openshift/src/main/fabric8/icon.svg
      fabric8.io/git-branch: release-v3.0.91
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
      fabric8.io/scm-tag: fabric8-team-components-1.0.0
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepository/io/fabric8/fabric8-team-components/apps/jenkins-openshift/3.0.91/jenkins-openshift-3.0.91.jar!/META-INF/fabric8/openshift.yml
    labels:
      app: jenkins-openshift
      provider: fabric8
      version: 3.0.91
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins
  spec:
    replicas: 1
    selector:
      app: jenkins-openshift
      provider: fabric8
      group: io.fabric8.fabric8-team-components.apps
    strategy:
      recreateParams:
        timeoutSeconds: 7200
      type: Recreate
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 419a7981d34eb123d464f03d3978c2b9a790f3df
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=jenkins-openshift&var-version=3.0.91
          fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
          fabric8.io/scm-url: http://github.com/fabric8io/fabric8-team-components/jenkins-openshift
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-team-components/master/jenkins-openshift/src/main/fabric8/icon.svg
          fabric8.io/target-platform: openshift
          configmap.fabric8.io/update-on-change: jenkins
          fabric8.io/git-branch: release-v3.0.91
          fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
          fabric8.io/scm-tag: fabric8-team-components-1.0.0
        labels:
          app: jenkins-openshift
          provider: fabric8
          version: 3.0.91
          group: io.fabric8.fabric8-team-components.apps
      spec:
        containers:
        - env:
          - name: PROJECT_NAMESPACE
            value: ${PROJECT_NAMESPACE}
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GIT_COMMITTER_EMAIL
            value: fabric8@googlegroups.com
          - name: GIT_COMMITTER_NAME
            value: fabric8
          - name: OPENSHIFT_ENABLE_OAUTH
            value: "true"
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: "true"
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: "true"
          - name: KUBERNETES_MASTER
            value: https://kubernetes.default:443
          - name: MAX_METASPACE_SIZE
            value: 200m
          - name: JENKINS_OPTS
            value: -Dgroovy.use.classvalue=true
          - name: RECOMMENDER_API_TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: jenkins-recommender-api-token
          image: fabric8/jenkins-openshift:vee53d43
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                - sh
                - /var/lib/jenkins/pre-shutdown.sh
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 420
            timeoutSeconds: 3
          name: jenkins
          ports:
          - containerPort: 50000
            name: slave
          - containerPort: 8080
            name: http
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: 700Mi
              cpu: "1500m"
            requests:
              cpu: "0"
          volumeMounts:
          - mountPath: /var/lib/jenkins
            name: jenkins-home
            readOnly: false
          - mountPath: /opt/openshift/configuration/
            name: jenkins-config
        - image: vpavlin/jenkins-proxy
          name: jenkins-proxy
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: "500m"
            requests:
              memory: 128Mi
              cpu: "250m"
          livenessProbe:
            exec:
              command: ["/opt/jenkins-proxy/health_check.sh"]
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command: ["/opt/jenkins-proxy/health_check.sh"]
            initialDelaySeconds: 5
            timeoutSeconds: 1
        serviceAccountName: jenkins
        volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
        - configMap:
            name: jenkins
          name: jenkins-config
    triggers:
    - type: ConfigChange
parameters:
- name: PROJECT_USER
  value: developer
- name: PROJECT_NAMESPACE
- name: RECOMMENDER_EXTERNAL_NAME
  value: recommender.api.prod-preview.openshift.io